import type { ProjectSchema } from '@nexcms/types';
import type { AstroFile } from './types.js';
import { buildPackageJson }   from './files/packageJson.js';
import { buildAstroConfig }   from './files/astroConfig.js';
import { buildTsConfig }      from './files/tsconfig.js';
import { buildBaseLayout }    from './layouts/Base.js';
import { buildIndexPage }     from './pages/index.js';
import { buildMenuPage }      from './pages/menu.js';
import { buildAboutPage }     from './pages/about.js';
import { buildContactPage }   from './pages/contact.js';
import { buildGlobalCss }     from './styles/global.js';
import { buildThemeCss }      from './styles/theme.js';
import { buildRobotsTxt }     from './files/robots.js';
import { buildSiteManifest }  from './files/manifest.js';
import { buildNavComponent }  from './components/Nav.js';
import { buildFooterComponent } from './components/Footer.js';
import { buildHeroComponent } from './components/Hero.js';
import { buildMenuComponent } from './components/MenuSection.js';
import { buildHoursComponent } from './components/HoursSection.js';
import { buildLocationComponent } from './components/LocationSection.js';
import { buildSocialComponent } from './components/SocialLinks.js';
import { buildGalleryComponent } from './components/Gallery.js';

export function buildAstroProject(schema: ProjectSchema): AstroFile[] {
  const files: AstroFile[] = [
    // Config / infra
    buildPackageJson(schema),
    buildAstroConfig(schema),
    buildTsConfig(),
    { path: 'src/env.d.ts', content: '/// <reference types="astro/client" />\n' },
    // Styles
    buildGlobalCss(schema),
    buildThemeCss(schema),
    // Layout
    buildBaseLayout(schema),
    // Components
    buildNavComponent(schema),
    buildFooterComponent(schema),
    buildHeroComponent(schema),
    buildMenuComponent(schema),
    buildHoursComponent(schema),
    buildLocationComponent(schema),
    buildSocialComponent(schema),
    buildGalleryComponent(schema),
    // Pages
    buildIndexPage(schema),
    buildMenuPage(schema),
    buildContactPage(schema),
    // Public / meta
    buildRobotsTxt(schema),
    buildSiteManifest(schema),
    { path: 'public/nexcms-site.json', content: JSON.stringify(schema, null, 2) + '\n' },
    { path: 'README.md', content: `# ${schema.business.name}\n\nGenerated by [NexCMS](https://nexcms.io).\n\n## Development\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Build\n\n\`\`\`bash\nnpm run build\n\`\`\`\n` },
  ];

  // Optional pages
  if (schema.blog?.length)    files.push(buildBlogIndex(schema), ...buildBlogPosts(schema));
  if (schema.events?.length)  files.push(buildEventsPage(schema));
  if (schema.business.description) files.push(buildAboutPage(schema));

  return files;
}

// ─ inline optional builders ────────────────────────────────────────────────────────
function buildBlogIndex(schema: ProjectSchema): AstroFile {
  const posts = schema.blog ?? [];
  const items = posts.map((p) =>
    `  <article class="blog-card">\n    <a href="/blog/${p.slug}"><h2>${p.title}</h2></a>\n    ${p.excerpt ? `<p>${p.excerpt}</p>` : ''}\n    ${p.publishedAt ? `<time>${p.publishedAt}</time>` : ''}\n  </article>`
  ).join('\n');
  return {
    path: 'src/pages/blog/index.astro',
    content: `---\nimport Base from '../../layouts/Base.astro';\n---\n<Base title="Blog — ${schema.business.name}">\n  <section class="section blog-index">\n    <div class="container">\n      <h1>Blog</h1>\n${items}\n    </div>\n  </section>\n</Base>\n`,
  };
}

function buildBlogPosts(schema: ProjectSchema): AstroFile[] {
  return (schema.blog ?? []).map((post) => ({
    path: `src/pages/blog/${post.slug}.astro`,
    content: `---\nimport Base from '../../../layouts/Base.astro';\n---\n<Base title="${post.title} — ${schema.business.name}">\n  <article class="section blog-post">\n    <div class="container prose">\n      <h1>${post.title}</h1>\n      ${post.publishedAt ? `<time class="post-date">${post.publishedAt}</time>` : ''}\n      <div class="post-body">${post.body}</div>\n    </div>\n  </article>\n</Base>\n`,
  }));
}

function buildEventsPage(schema: ProjectSchema): AstroFile {
  const events = schema.events ?? [];
  const items = events.map((e) =>
    `  <div class="event-card">\n    <h3>${e.name}</h3>\n    ${e.date ? `<time>${e.date}${e.time ? ' at ' + e.time : ''}</time>` : ''}\n    ${e.description ? `<p>${e.description}</p>` : ''}\n    ${e.ticketUrl ? `<a class="btn btn-sm" href="${e.ticketUrl}" target="_blank" rel="noreferrer">Tickets</a>` : ''}\n  </div>`
  ).join('\n');
  return {
    path: 'src/pages/events.astro',
    content: `---\nimport Base from '../layouts/Base.astro';\n---\n<Base title="Events — ${schema.business.name}">\n  <section class="section events-page">\n    <div class="container">\n      <h1>Events</h1>\n${items}\n    </div>\n  </section>\n</Base>\n`,
  };
}
