// Creates a minimal valid ProjectSchema for plated init
import type { ProjectSchema } from '@plated/types';

export function createDefaultSchema(name: string): ProjectSchema {
  return {
    id: crypto.randomUUID(),
    schemaVersion: '2.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    businessType: 'restaurant',
    styleTemplate: 'hearth',
    colorTheme: 'default',
    darkMode: false,
    business: {
      name,
      tagline: '',
      description: '',
      phone: '',
      email: '',
      cuisineType: '',
      existingWebsite: '',
    },
    branding: {
      logoUrl: '',
      heroImageUrl: '',
      heroVideoUrl: '',
      primaryColor: '#8a4b2f',
      secondaryColor: '#f4ede4',
      accentColor: '#c98f4a',
      faviconSourceUrl: '',
    },
    locations: [],
    primaryLocationIndex: 0,
    menu: {
      categories: [],
    },
    social: {
      facebook: '',
      instagram: '',
      twitter: '',
      tiktok: '',
      youtube: '',
      googleBusiness: '',
      yelp: '',
      tripadvisor: '',
      doordash: '',
      ubereats: '',
      grubhub: '',
      toast: '',
      chownow: '',
      opentable: '',
    },
    integrations: {},
    seo: {
      siteTitle: name,
      metaDescription: '',
      googleVerification: '',
      bingVerification: '',
      headSnippet: '',
      bodyStartSnippet: '',
      bodyEndSnippet: '',
    },
    extensions: {},
    deployment: {
      subdomain: '',
      customDomain: '',
    },
    blog: [],
    events: [],
    specials: [],
    press: [],
  } satisfies ProjectSchema;
}
