/**
 * theme.ts — embeds a theme's variables.css into the generated Astro project.
 *
 * Strategy:
 *   At generation time (Node.js context), we read the selected theme's
 *   variables.css from disk and embed it verbatim into src/styles/theme.css.
 *   The CSS uses [data-theme][data-variant] selectors which are matched by the
 *   data-theme / data-variant attributes on <html> (set in Base.astro).
 *
 *   If the file is missing we emit a minimal fallback :root {} block so the
 *   generator never throws — this makes dry-run and unit tests safe.
 */
import { readFileSync } from 'node:fs';
import { resolve }     from 'node:path';
import { existsSync }  from 'node:fs';
import type { ProjectSchema } from '@plated/types';
import type { AstroFile }    from '../types.js';

/** Minimal fallback token set when variables.css cannot be found on disk. */
const FALLBACK_TOKENS = `
/* Plated — fallback tokens (theme file not found at build time) */
:root {
  --color-bg-base:          #fafafa;
  --color-bg-surface:       #f4f4f4;
  --color-bg-elevated:      #ebebeb;
  --color-text-primary:     #111111;
  --color-text-secondary:   #444444;
  --color-text-muted:       #888888;
  --color-text-inverse:     #ffffff;
  --color-accent-primary:   #2563eb;
  --color-accent-secondary: #60a5fa;
  --color-accent-pale:      rgba(37,99,235,0.10);
  --color-border:           #d1d5db;
  --color-border-subtle:    #e5e7eb;
  --shadow-sm: 0 1px 2px rgba(0,0,0,0.06);
  --shadow-md: 0 4px 10px rgba(0,0,0,0.09);
  --shadow-lg: 0 8px 24px rgba(0,0,0,0.13);
  --font-sans:    system-ui, sans-serif;
  --font-display: system-ui, sans-serif;
  --font-mono:    'Courier New', monospace;
  --space-1:  0.25rem; --space-2:  0.5rem;  --space-3:  0.75rem;
  --space-4:  1rem;    --space-6:  1.5rem;  --space-8:  2rem;
  --space-12: 3rem;    --space-16: 4rem;
  --radius-sm: 0.25rem; --radius-md: 0.5rem; --radius-lg: 0.75rem; --radius-full: 9999px;
}
`;

/**
 * Resolves the absolute path to a theme's variables.css.
 * Mirrors the logic in packages/generator/src/themeRegistry.ts but
 * expressed relative to this file so astro-output has no circular dep.
 */
function resolveVariablesCss(themeId: string): string {
  // 1. Env override (set by Electron / production build)
  const envDir = process.env['PLATED_STYLES_DIR'];
  if (envDir) {
    const c = `${envDir}/${themeId}/variables.css`;
    if (existsSync(c)) return c;
  }
  // 2. Repo-relative from packages/astro-output/src/styles/
  return resolve(
    typeof __dirname !== 'undefined'
      ? __dirname
      : new URL('.', import.meta.url).pathname,
    '../../../../styles',
    themeId,
    'variables.css',
  );
}

export function buildThemeCss(schema: ProjectSchema): AstroFile {
  const themeId  = schema.styleTemplate ?? 'hearth';
  const cssPath  = resolveVariablesCss(themeId);

  let variablesCss: string;
  try {
    variablesCss = readFileSync(cssPath, 'utf-8');
  } catch {
    console.warn(
      `[plated] theme variables.css not found for "${themeId}" at ${cssPath}. Using fallback tokens.`,
    );
    variablesCss = FALLBACK_TOKENS;
  }

  // ── Brand colour overrides ───────────────────────────────────────────────
  // If the user chose custom brand colours in the wizard, they win over the
  // theme defaults. We inject them as a [data-theme] override block so they
  // take precedence without duplicating the full token set.
  const overrides: string[] = [];
  if (schema.branding.primaryColor) {
    overrides.push(`  --color-accent-primary:   ${schema.branding.primaryColor};`);
  }
  if (schema.branding.secondaryColor) {
    overrides.push(`  --color-bg-surface:       ${schema.branding.secondaryColor};`);
  }
  if (schema.branding.accentColor) {
    overrides.push(`  --color-accent-secondary: ${schema.branding.accentColor};`);
  }

  const overrideBlock = overrides.length
    ? `\n/* ── Brand colour overrides (from wizard) ── */\n[data-theme="${themeId}"] {\n${overrides.join('\n')}\n}\n`
    : '';

  return {
    path:    'src/styles/theme.css',
    content: `/* Generated by Plated — do not edit. Theme: ${themeId} */\n${variablesCss}${overrideBlock}`,
  };
}
